[workspace.package]
version = "0.0.0"
authors = ["PostDude"]
repository = "https://github.com/ludblom/postdude-app/"
license = "GPL-3.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "postdude-lib",
    "postdude-cli",
    "postdude-types",
]
